### ISSUE TITLE
Same directory

### ISSUE THREAD

**Issue by qm3ster** [QuantumSheep/warshield-cli#4]
I feel like decrypting the files in place or alongside the encrypted files is a default that is likely to cause disasters.
For instance, if used on an untrustworthy network share, you will end up writing the defenceless files to the network share.
With a usb stick, you might leave the unencrypted files on it (possibly having deleted most but not all).

I would have suggested a temporary directory, but even that doesn't get cleaned up even in case of a reboot in many cases, and users, not being able to locate it, might think it is gone.

**Comment by quantumsheep** [comment]
I know that if a user stops a WarShield's process, the .warshield files will stay. But there is no way to fix that, first we can prevent the SIGNINT usage in order to delete the files before stopping the process. But in case of a kill, there's nothing we can do :(

A temporary directory may be a good solution after all, even if .warshield files doesn't get cleaned up, they could be deleted easier than now.

**Comment by qm3ster** [comment]
Maybe a `DECRYPTED/` subdir for now, which people would know to atomically delete?
Doesn't solve the hostile drive issue, but better than intermingling the files for sure.

**Comment by quantumsheep** [comment]
I was thinking about a random `tmp` directory to prevent an attacker to guess where are the decrypted/encrypted temporary files.

Sure that it doesn't really solve the issue but there is no way to find a fix to that, if a process stops, it stops, no matter what :(

**Comment by qm3ster** [comment]
If it's random, two acts of decryption might leave two copies of the files under the same directory, and then the user only deletes one.

**Comment by quantumsheep** [comment]
Fixed in https://github.com/quantumsheep/warshield/commit/9dce975467b56f1486bea9462fd41d86e39d7cb1 and https://github.com/quantumsheep/warshield/commit/f5aaee59d1a039c2c76f73d0c75d71a0e174ab47 😄
